# services:
#   nginx:
#     build: ./src/requirement/nginx
#     container_name: nginx
#     ports:
#       - "80:80"
#     networks:
#       - my_network
#     depends_on:
#       - wordpress

#   wordpress:
#     build: ./src/requirement/wordpress
#     container_name: wordpress
#     environment:
#       WORDPRESS_DB_HOST: ${{DB_HOST}}
#       WORDPRESS_DB_USER: votre_utilisateur
#       WORDPRESS_DB_PASSWORD: votre_mot_de_passe
#       WORDPRESS_DB_NAME: votre_base
#     networks:
#       - my_network
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: votre_mot_de_passe_root
#       MYSQL_DATABASE: votre_base
#       MYSQL_USER: votre_utilisateur
#       MYSQL_PASSWORD: votre_mot_de_passe
#     networks:
#       - my_network