services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file:
      - ${PATH_ENV}
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      NAME_DATABASE: ${NAME_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception
    restart: on-failure


  nginx:
      build:
        context: requirements/nginx
        dockerfile: Dockerfile
      container_name: nginx
      image: nginx
      ports:
        - "443:443"
      networks:
        - inception
      restart: unless-stopped

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    env_file:
      - ${PATH_ENV}
    environment:
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_USER_USERNAME: ${WP_USER_USERNAME}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    networks:
      - inception
    restart: on-failure


volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ${PATH_SECRETS_DB_PASS}
  db_root_password:
    file: ${PATH_SECRETS_DB_ROOT_PASS}